"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000/api";
function auth(){return {Authorization:`Bearer ${localStorage.getItem("admin_token")||""}`}}

export default function AdminPage(){
 const router=useRouter();
 const [stats,setStats]=useState<any>({}); const [products,setProducts]=useState<any[]>([]);
 const [q,setQ]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 const [importImages,setImportImages]=useState<File[]>([]); const [csvFile,setCsvFile]=useState<File|null>(null);
 const [jobs,setJobs]=useState<any[]>([]); const [selectedJob,setSelectedJob]=useState<any>(null); const [edit,setEdit]=useState<any>(null); const [file,setFile]=useState<File|null>(null);
 const timer=useRef<ReturnType<typeof setInterval>|null>(null);
 async function load(){const h=auth();const [s,p,j]=await Promise.all([fetch(`${API}/admin/stats`,{headers:h}),fetch(`${API}/products?limit=50`),fetch(`${API}/admin/import-jobs`,{headers:h})]);if(s.status===401){router.push("/admin/login");return}setStats(await s.json());setProducts((await p.json()).items||[]);if(j.ok)setJobs(await j.json())}
 useEffect(()=>{if(!localStorage.getItem("admin_token"))router.push("/admin/login");else load();return()=>{if(timer.current)clearInterval(timer.current)}},[]);
 async function importCsv(){if(!csvFile){setMessage("CSV file নির্বাচন করুন।");return}if(csvFile.size>8*1024*1024){setMessage("CSV সর্বোচ্চ 8 MB হতে পারবে।");return}if(importImages.length>3000){setMessage("একবারে সর্বোচ্চ 3000টি image upload করুন।");return}setBusy(true);setMessage("CSV ও images upload হচ্ছে... page বন্ধ করবেন না।");const fd=new FormData();fd.append("file",csvFile);importImages.forEach(img=>fd.append("images",img));const r=await fetch(`${API}/products/import`,{method:"POST",headers:auth(),body:fd});const d=await r.json();setMessage(r.ok?`Import queued: ${d.id}`:(d.message||"Import failed"));if(r.ok){setCsvFile(null);setImportImages([]);startPolling(d.id)}setBusy(false);await load()}
 function startPolling(id:string){if(timer.current)clearInterval(timer.current);timer.current=setInterval(async()=>{const r=await fetch(`${API}/admin/import-jobs/${id}`,{headers:auth()});if(!r.ok)return;const d=await r.json();setSelectedJob(d);setJobs(prev=>prev.map(j=>j.id===d.id?d:j));if(["COMPLETED","FAILED"].includes(d.status)){if(timer.current)clearInterval(timer.current);setMessage(d.status==="COMPLETED"?`Import completed: ${d.imported} imported, ${d.failed} failed.`:`Import failed: ${d.message||"worker error"}`);load()}},1500)}
 async function openJob(id:string){const r=await fetch(`${API}/admin/import-jobs/${id}`,{headers:auth()});if(r.ok)setSelectedJob(await r.json())}
 async function retry(id:string){setBusy(true);const r=await fetch(`${API}/admin/import-jobs/${id}/retry`,{method:"POST",headers:auth()});const d=await r.json();setMessage(r.ok?"Import queued again.":d.message||"Retry failed");if(r.ok)startPolling(id);setBusy(false);load()}
 async function rebuild(){setBusy(true);const r=await fetch(`${API}/admin/search/rebuild`,{method:"POST",headers:auth()});const d=await r.json();setMessage(r.ok?`Indexed ${d.indexed} products.`:"Index failed");setBusy(false)}
 async function search(){if(!q.trim())return load();const d=await fetch(`${API}/search?q=${encodeURIComponent(q)}`).then(r=>r.json());setProducts(d.hits||[])}
 return <main className="admin"><div className="adminTop"><div><h1>Admin Panel</h1><p>Catalog, bulk import, image processing and Meilisearch</p></div><div><button className="button secondary" onClick={()=>{localStorage.removeItem("admin_token");router.push("/admin/login")}}>Logout</button> <a href="/">Store</a></div></div>
 <div className="stats">{[["Products",stats.products],["Active",stats.activeProducts],["Categories",stats.categories],["Brands",stats.brands]].map(([l,v])=><div className="stat" key={String(l)}><b>{v??"—"}</b><span>{l}</span></div>)}</div>
 <section className="adminCard"><h2>⚡ Bulk Product Import</h2><p className="formHint">CSV-তে শুধু product তথ্য দিলেই হবে। SEO title, meta description, slug, image processing এবং Meilisearch indexing automatically হবে। CSV-এর <b>imageFile/image2/image3</b> column-এর filename-এর সাথে selected image filename মিলতে হবে।</p>
 <div className="actions"><a className="button secondary" href={`${API}/admin/import-template`} target="_blank">Download CSV Template</a><label className="button secondary">Choose CSV + Images<input hidden multiple type="file" accept=".csv,image/*" onChange={e=>{const fs=Array.from(e.target.files||[]);setCsvFile(fs.find(f=>f.name.toLowerCase().endsWith(".csv"))||null);setImportImages(fs.filter(f=>f.type.startsWith("image/")))}}/></label><span>{csvFile?`CSV: ${csvFile.name} (${(csvFile.size/1024/1024).toFixed(1)} MB)`:'No CSV selected'}{importImages.length?` • ${importImages.length} image(s)`:''}</span><button className="button" disabled={busy||!csvFile} onClick={importCsv}>{busy?"Uploading...":"Start Import"}</button><button className="button secondary" disabled={busy} onClick={rebuild}>Rebuild Meilisearch</button></div>{message&&<div className="notice">{message}</div>}
 </section>
 {selectedJob&&<section className="adminCard"><h2>Import Progress</h2><div><b>{selectedJob.status}</b> — {selectedJob.processed}/{selectedJob.total||"?"} rows • {selectedJob.imported} imported • {selectedJob.failed} failed</div><div style={{marginTop:10,height:12,background:"#eee",borderRadius:8,overflow:"hidden"}}><div style={{height:"100%",width:`${selectedJob.total?Math.min(100,Math.round(selectedJob.processed/selectedJob.total*100)):0}%`}}/></div>{selectedJob.errors?.length?<div className="notice">Last {selectedJob.errors.length} errors: {selectedJob.errors.map((e:any,i:number)=><div key={i}>Row {e.row??"?"}: {e.message}</div>)}<a className="button secondary" href={`${API}/admin/import-jobs/${selectedJob.id}/errors.csv`} target="_blank">Download Error CSV</a></div>:null}</section>}
 <section className="adminCard"><h2>Import Jobs</h2><div className="tableWrap"><table><thead><tr><th>File</th><th>Status</th><th>Progress</th><th>Imported</th><th>Failed</th><th>Action</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td>{j.fileName}</td><td>{j.status}</td><td>{j.processed}/{j.total||"—"}</td><td>{j.imported}</td><td>{j.failed}</td><td><button onClick={()=>openJob(j.id)}>View</button>{["FAILED","COMPLETED"].includes(j.status)&&j.failed>0?<button onClick={()=>retry(j.id)} disabled={busy}>Retry</button>:null}</td></tr>)}</tbody></table></div></section>
 <section className="adminCard"><div className="tableHead"><h2>Products</h2><div className="searchBox"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search..." onKeyDown={e=>e.key==="Enter"&&search()}/><button onClick={search}>Search</button></div></div><div className="tableWrap"><table><thead><tr><th>Image</th><th>Product</th><th>SKU</th><th>Price</th><th>Stock</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.imageUrl?<img className="thumb" src={p.imageUrl} alt={p.name||"Product"}/>:"—"}</td><td>{p.name}</td><td>{p.sku}</td><td>৳{Number(p.price).toLocaleString("en-BD")}</td><td>{p.stock}</td></tr>)}</tbody></table></div></section></main>
}
