"use client";
import { useEffect, useMemo, useState } from "react";
type CartItem = { key?:string; id:string; variantId?:string|null; variantName?:string|null; name:string; sku?:string; price:string|number; quantity:number; stock:number; imageUrl?:string|null };
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000/api";
const CART_KEY = "gulshan_cart_v1";
export default function CheckoutPage() {
 const [cart,setCart]=useState<CartItem[]>([]),[couponCode,setCouponCode]=useState(""),[quote,setQuote]=useState<any>(null),[customerName,setCustomerName]=useState(""),[mobile,setMobile]=useState(""),[address,setAddress]=useState(""),[email,setEmail]=useState(""),[city,setCity]=useState("Dhaka"),[area,setArea]=useState(""),[customerId,setCustomerId]=useState<string|undefined>(),[paymentMethod,setPaymentMethod]=useState("COD"),[loading,setLoading]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState<any>(null);
 useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem(CART_KEY)||"[]"));}catch{setCart([])}const t=localStorage.getItem("customer_token");if(t)fetch(`${API}/customer/me`,{headers:{Authorization:`Bearer ${t}`}}).then(r=>r.ok?r.json():null).then(c=>{if(c){setCustomerId(c.id);setCustomerName(c.name);setMobile(c.mobile);setEmail(c.email||"")}})},[]);
 const fallbackTotal=useMemo(()=>cart.reduce((s,x)=>s+Number(x.price)*x.quantity,0),[cart]);
 const total=quote?.total??fallbackTotal;
 useEffect(()=>{if(!cart.length)return;const t=localStorage.getItem("customer_token");fetch(`${API}/checkout/quote`,{method:"POST",headers:{"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})},body:JSON.stringify({items:cart.map(x=>({productId:x.id,variantId:x.variantId||undefined,quantity:x.quantity})),couponCode,city,area})}).then(r=>r.ok?r.json():null).then(setQuote).catch(()=>{});},[cart,city,area,couponCode]);
 const save=(next:CartItem[])=>{setCart(next);localStorage.setItem(CART_KEY,JSON.stringify(next));};
 const updateQty=(id:string,q:number)=>save(cart.map(x=>((x.key||x.id)===id)?{...x,quantity:Math.max(1,Math.min(q,x.stock))}:x));
 const remove=(id:string)=>save(cart.filter(x=>(x.key||x.id)!==id));
 const placeOrder=async(e:React.FormEvent)=>{e.preventDefault();setError("");if(!cart.length)return setError("Your cart is empty.");setLoading(true);try{const r=await fetch(`${API}/orders`,{method:"POST",headers:{"Content-Type":"application/json",...(localStorage.getItem("customer_token")?{Authorization:`Bearer ${localStorage.getItem("customer_token")}`}:{})},body:JSON.stringify({customerName,mobile,address,email,city,area,paymentMethod,couponCode,items:cart.map(x=>({productId:x.id,variantId:x.variantId||undefined,quantity:x.quantity}))})});const data=await r.json();if(!r.ok)throw new Error(data.message||"Order failed");fetch(`${API}/events`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"purchase",path:"/checkout",orderId:data.id,metadata:{total:Number(data.total)}})}).catch(()=>{});localStorage.removeItem(CART_KEY);setCart([]);setSuccess(data);}catch(e:any){setError(e.message||"Order failed")}finally{setLoading(false)}};
 if(success)return <main className="checkoutPage"><div className="checkoutCard"><h1>Order Confirmed</h1><p>Thank you, {success.customerName}.</p><p>Order ID: <b>{success.id}</b></p><p>Total: <b>৳{Number(success.total).toLocaleString("en-BD")}</b></p><a className="checkoutButton" href="/">Continue Shopping</a></div></main>;
 return <main className="checkoutPage"><div className="checkoutWrap"><div className="checkoutHeader"><a href="/">← Continue Shopping</a><h1>Cart & Checkout</h1></div>{!cart.length?<div className="checkoutCard"><p>Your cart is empty.</p><a className="checkoutButton" href="/">Shop Products</a></div>:<div className="checkoutLayout"><section className="checkoutCard"><h2>Your Cart</h2>{cart.map(item=><div className="cartItem" key={item.key||`${item.id}:${item.variantId||"base"}`}>{item.imageUrl?<img src={item.imageUrl} alt={item.name}/>:<div className="cartThumb">No image</div>}<div className="cartInfo"><b>{item.name}</b>{item.variantName&&<small>{item.variantName}</small>}<span>৳{Number(item.price).toLocaleString("en-BD")}</span><div><button onClick={()=>updateQty(item.key||item.id,item.quantity-1)} disabled={item.quantity<=1}>−</button><span>{item.quantity}</span><button onClick={()=>updateQty(item.key||item.id,item.quantity+1)} disabled={item.quantity>=item.stock}>+</button><button className="removeButton" onClick={()=>remove(item.key||item.id)}>Remove</button></div></div></div>)}<div className="checkoutTotal">Total <b>৳{total.toLocaleString("en-BD")}</b></div></section><form className="checkoutCard checkoutForm" onSubmit={placeOrder}><h2>Delivery Information</h2><label>Name<input value={customerName} onChange={e=>setCustomerName(e.target.value)} required/></label><label>Mobile<input value={mobile} onChange={e=>setMobile(e.target.value)} required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>City<input value={city} onChange={e=>setCity(e.target.value)}/></label><label>Area<input value={area} onChange={e=>setArea(e.target.value)}/></label><label>Address<textarea value={address} onChange={e=>setAddress(e.target.value)} required rows={4}/></label><label>Coupon code<input value={couponCode} onChange={e=>setCouponCode(e.target.value.toUpperCase())} placeholder="Optional coupon"/></label><div className="codNote">{quote?`Subtotal ৳${Number(quote.subtotal).toLocaleString("en-BD")} • Discount ৳${Number(quote.discount).toLocaleString("en-BD")} • Delivery ৳${Number(quote.shipping).toLocaleString("en-BD")}`:""}</div><label>Payment<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}><option value="COD">Cash on Delivery</option><option value="ONLINE" disabled>Online Payment (configure gateway first)</option></select></label><div className="codNote">COD is active. Online payment is kept disabled until merchant credentials are configured.</div>{error&&<p className="error">{error}</p>}<button className="checkoutButton" disabled={loading}>{loading?"Placing Order...":"Place Order"}</button></form></div>}</div></main>;
}
