import type { Metadata } from "next";
import { notFound } from "next/navigation";
import ProductGrid from "../../product-grid";
import { absoluteUrl, brandTitle, safeJsonLd, truncate } from "../../../lib/seo";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000/api";
async function getBrand(slug:string){try{const r=await fetch(`${API}/brands`,{cache:"no-store"});if(!r.ok)return null;const xs=await r.json();return xs.find((x:any)=>x.slug===slug)||null}catch{return null}}
export const dynamic="force-dynamic";
export async function generateMetadata({params,searchParams}:{params:Promise<{slug:string}>,searchParams:Promise<Record<string,string|string[]|undefined>>}):Promise<Metadata>{const {slug}=await params;const sp=await searchParams;if(Object.keys(sp).length)return{title:"Browse",robots:{index:false,follow:true},alternates:{canonical: absoluteUrl(`/brand/${slug}`)}};const b=await getBrand(slug);if(!b)return{title:"Brand not found",robots:{index:false,follow:true}};const url=absoluteUrl(`/brand/${b.slug}`);return{title:brandTitle(b),description:truncate(b.description||`Shop ${b.name} products in Bangladesh at Gulshan Bazar.`),alternates:{canonical:url},robots:{index:true,follow:true},openGraph:{title:brandTitle(b),description:truncate(b.description||`Shop ${b.name} products in Bangladesh.`),url}}}
export default async function BrandPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const b=await getBrand(slug);if(!b)notFound();const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:absoluteUrl("/")},{"@type":"ListItem",position:2,name:b.name,item:absoluteUrl(`/brand/${b.slug}`)}]};return <main className="container section"><nav aria-label="Breadcrumb"><a href="/">Home</a> / <span>{b.name}</span></nav><h1>{b.name}</h1>{b.description&&<p>{b.description}</p>}<ProductGrid initialBrandId={b.id}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(breadcrumb)}}/></main>}
