import type { Metadata } from "next";
import { notFound } from "next/navigation";
import ProductGrid from "../../product-grid";
import { absoluteUrl, categoryTitle, safeJsonLd, truncate } from "../../../lib/seo";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000/api";
async function getCategory(slug:string){try{const r=await fetch(`${API}/categories`,{cache:"no-store"});if(!r.ok)return null;const xs=await r.json();return xs.find((x:any)=>x.slug===slug)||null}catch{return null}}
export const dynamic="force-dynamic";
export async function generateMetadata({params,searchParams}:{params:Promise<{slug:string}>,searchParams:Promise<Record<string,string|string[]|undefined>>}):Promise<Metadata>{const {slug}=await params;const sp=await searchParams;if(Object.keys(sp).length)return{title:"Browse",robots:{index:false,follow:true},alternates:{canonical: absoluteUrl(`/category/${slug}`)}};const c=await getCategory(slug);if(!c)return{title:"Category not found",robots:{index:false,follow:true}};const url=absoluteUrl(`/category/${c.slug}`);return{title:categoryTitle(c),description:truncate(c.description||`Browse ${c.name} products in Bangladesh at Gulshan Bazar.`),alternates:{canonical:url},robots:{index:true,follow:true},openGraph:{title:categoryTitle(c),description:truncate(c.description||`Browse ${c.name} products in Bangladesh.`),url}}}
export default async function CategoryPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const c=await getCategory(slug);if(!c)notFound();const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:absoluteUrl("/")},{"@type":"ListItem",position:2,name:c.name,item:absoluteUrl(`/category/${c.slug}`)}]};return <main className="container section"><nav aria-label="Breadcrumb"><a href="/">Home</a> / <span>{c.name}</span></nav><h1>{c.name}</h1>{c.description&&<p>{c.description}</p>}<ProductGrid initialCategoryId={c.id}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(breadcrumb)}}/></main>}
